export const getNextRepo = () => {
  return {
    id: 70107786,
    node_id: "MDEwOlJlcG9zaXRvcnk3MDEwNzc4Ng==",
    name: "next.js",
    full_name: "vercel/next.js",
    private: false,
    owner: {
      login: "vercel",
      id: 14985020,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw",
      avatar_url: "https://avatars.githubusercontent.com/u/14985020?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/vercel",
      html_url: "https://github.com/vercel",
      followers_url: "https://api.github.com/users/vercel/followers",
      following_url:
        "https://api.github.com/users/vercel/following{/other_user}",
      gists_url: "https://api.github.com/users/vercel/gists{/gist_id}",
      starred_url: "https://api.github.com/users/vercel/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/vercel/subscriptions",
      organizations_url: "https://api.github.com/users/vercel/orgs",
      repos_url: "https://api.github.com/users/vercel/repos",
      events_url: "https://api.github.com/users/vercel/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/vercel/received_events",
      type: "Organization",
      site_admin: false,
    },
    html_url: "https://github.com/vercel/next.js",
    description: "The React Framework",
    fork: false,
    url: "https://api.github.com/repos/vercel/next.js",
    forks_url: "https://api.github.com/repos/vercel/next.js/forks",
    keys_url: "https://api.github.com/repos/vercel/next.js/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/vercel/next.js/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/vercel/next.js/teams",
    hooks_url: "https://api.github.com/repos/vercel/next.js/hooks",
    issue_events_url:
      "https://api.github.com/repos/vercel/next.js/issues/events{/number}",
    events_url: "https://api.github.com/repos/vercel/next.js/events",
    assignees_url:
      "https://api.github.com/repos/vercel/next.js/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/vercel/next.js/branches{/branch}",
    tags_url: "https://api.github.com/repos/vercel/next.js/tags",
    blobs_url: "https://api.github.com/repos/vercel/next.js/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/vercel/next.js/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/vercel/next.js/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/vercel/next.js/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/vercel/next.js/statuses/{sha}",
    languages_url: "https://api.github.com/repos/vercel/next.js/languages",
    stargazers_url: "https://api.github.com/repos/vercel/next.js/stargazers",
    contributors_url:
      "https://api.github.com/repos/vercel/next.js/contributors",
    subscribers_url: "https://api.github.com/repos/vercel/next.js/subscribers",
    subscription_url:
      "https://api.github.com/repos/vercel/next.js/subscription",
    commits_url: "https://api.github.com/repos/vercel/next.js/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/vercel/next.js/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/vercel/next.js/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/vercel/next.js/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/vercel/next.js/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/vercel/next.js/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/vercel/next.js/merges",
    archive_url:
      "https://api.github.com/repos/vercel/next.js/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/vercel/next.js/downloads",
    issues_url: "https://api.github.com/repos/vercel/next.js/issues{/number}",
    pulls_url: "https://api.github.com/repos/vercel/next.js/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/vercel/next.js/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/vercel/next.js/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/vercel/next.js/labels{/name}",
    releases_url: "https://api.github.com/repos/vercel/next.js/releases{/id}",
    deployments_url: "https://api.github.com/repos/vercel/next.js/deployments",
    created_at: "2016-10-05T23:32:51Z",
    updated_at: "2022-06-19T01:04:23Z",
    pushed_at: "2022-06-19T00:00:14Z",
    git_url: "git://github.com/vercel/next.js.git",
    ssh_url: "git@github.com:vercel/next.js.git",
    clone_url: "https://github.com/vercel/next.js.git",
    svn_url: "https://github.com/vercel/next.js",
    homepage: "https://nextjs.org",
    size: 1755418,
    stargazers_count: 88231,
    watchers_count: 88231,
    language: "JavaScript",
    has_issues: true,
    has_projects: false,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 18846,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 1206,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    topics: [
      "blog",
      "browser",
      "compiler",
      "components",
      "hybrid",
      "nextjs",
      "node",
      "react",
      "server-rendering",
      "ssg",
      "static",
      "static-site-generator",
      "universal",
      "vercel",
    ],
    visibility: "public",
    forks: 18846,
    open_issues: 1206,
    watchers: 88231,
    default_branch: "canary",
    temp_clone_token: null,
    organization: {
      login: "vercel",
      id: 14985020,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw",
      avatar_url: "https://avatars.githubusercontent.com/u/14985020?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/vercel",
      html_url: "https://github.com/vercel",
      followers_url: "https://api.github.com/users/vercel/followers",
      following_url:
        "https://api.github.com/users/vercel/following{/other_user}",
      gists_url: "https://api.github.com/users/vercel/gists{/gist_id}",
      starred_url: "https://api.github.com/users/vercel/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/vercel/subscriptions",
      organizations_url: "https://api.github.com/users/vercel/orgs",
      repos_url: "https://api.github.com/users/vercel/repos",
      events_url: "https://api.github.com/users/vercel/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/vercel/received_events",
      type: "Organization",
      site_admin: false,
    },
    network_count: 18846,
    subscribers_count: 1273,
  };
};

export const getPreactRepo = () => {
  return {
    id: 42283287,
    node_id: "MDEwOlJlcG9zaXRvcnk0MjI4MzI4Nw==",
    name: "preact",
    full_name: "preactjs/preact",
    private: false,
    owner: {
      login: "preactjs",
      id: 26872990,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjI2ODcyOTkw",
      avatar_url: "https://avatars.githubusercontent.com/u/26872990?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/preactjs",
      html_url: "https://github.com/preactjs",
      followers_url: "https://api.github.com/users/preactjs/followers",
      following_url:
        "https://api.github.com/users/preactjs/following{/other_user}",
      gists_url: "https://api.github.com/users/preactjs/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/preactjs/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/preactjs/subscriptions",
      organizations_url: "https://api.github.com/users/preactjs/orgs",
      repos_url: "https://api.github.com/users/preactjs/repos",
      events_url: "https://api.github.com/users/preactjs/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/preactjs/received_events",
      type: "Organization",
      site_admin: false,
    },
    html_url: "https://github.com/preactjs/preact",
    description:
      "⚛️ Fast 3kB React alternative with the same modern API. Components & Virtual DOM.",
    fork: false,
    url: "https://api.github.com/repos/preactjs/preact",
    forks_url: "https://api.github.com/repos/preactjs/preact/forks",
    keys_url: "https://api.github.com/repos/preactjs/preact/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/preactjs/preact/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/preactjs/preact/teams",
    hooks_url: "https://api.github.com/repos/preactjs/preact/hooks",
    issue_events_url:
      "https://api.github.com/repos/preactjs/preact/issues/events{/number}",
    events_url: "https://api.github.com/repos/preactjs/preact/events",
    assignees_url:
      "https://api.github.com/repos/preactjs/preact/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/preactjs/preact/branches{/branch}",
    tags_url: "https://api.github.com/repos/preactjs/preact/tags",
    blobs_url: "https://api.github.com/repos/preactjs/preact/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/preactjs/preact/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/preactjs/preact/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/preactjs/preact/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/preactjs/preact/statuses/{sha}",
    languages_url: "https://api.github.com/repos/preactjs/preact/languages",
    stargazers_url: "https://api.github.com/repos/preactjs/preact/stargazers",
    contributors_url:
      "https://api.github.com/repos/preactjs/preact/contributors",
    subscribers_url: "https://api.github.com/repos/preactjs/preact/subscribers",
    subscription_url:
      "https://api.github.com/repos/preactjs/preact/subscription",
    commits_url: "https://api.github.com/repos/preactjs/preact/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/preactjs/preact/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/preactjs/preact/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/preactjs/preact/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/preactjs/preact/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/preactjs/preact/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/preactjs/preact/merges",
    archive_url:
      "https://api.github.com/repos/preactjs/preact/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/preactjs/preact/downloads",
    issues_url: "https://api.github.com/repos/preactjs/preact/issues{/number}",
    pulls_url: "https://api.github.com/repos/preactjs/preact/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/preactjs/preact/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/preactjs/preact/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/preactjs/preact/labels{/name}",
    releases_url: "https://api.github.com/repos/preactjs/preact/releases{/id}",
    deployments_url: "https://api.github.com/repos/preactjs/preact/deployments",
    created_at: "2015-09-11T02:40:18Z",
    updated_at: "2022-06-18T21:32:31Z",
    pushed_at: "2022-06-17T22:44:07Z",
    git_url: "git://github.com/preactjs/preact.git",
    ssh_url: "git@github.com:preactjs/preact.git",
    clone_url: "https://github.com/preactjs/preact.git",
    svn_url: "https://github.com/preactjs/preact",
    homepage: "https://preactjs.com",
    size: 12588,
    stargazers_count: 31849,
    watchers_count: 31849,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 1781,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 227,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    topics: [
      "components",
      "dom",
      "jsx",
      "preact",
      "react",
      "vdom",
      "virtual-dom",
    ],
    visibility: "public",
    forks: 1781,
    open_issues: 227,
    watchers: 31849,
    default_branch: "master",
    temp_clone_token: null,
    organization: {
      login: "preactjs",
      id: 26872990,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjI2ODcyOTkw",
      avatar_url: "https://avatars.githubusercontent.com/u/26872990?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/preactjs",
      html_url: "https://github.com/preactjs",
      followers_url: "https://api.github.com/users/preactjs/followers",
      following_url:
        "https://api.github.com/users/preactjs/following{/other_user}",
      gists_url: "https://api.github.com/users/preactjs/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/preactjs/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/preactjs/subscriptions",
      organizations_url: "https://api.github.com/users/preactjs/orgs",
      repos_url: "https://api.github.com/users/preactjs/repos",
      events_url: "https://api.github.com/users/preactjs/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/preactjs/received_events",
      type: "Organization",
      site_admin: false,
    },
    network_count: 1781,
    subscribers_count: 417,
  };
};